mode: Test
# Test | xiaorong
Test: {
    'beauty': {
        train: True,
        dataset_no: 0,
        fold_no: [0], # 0 | 1 | 2 | 3 | 4
        train_batch_size: 10000,
        test_batch_size: 10000,
        epochs: 60000,
        gen_hidden: 20000,
        gen_output_activation: 'sigmoid',
        gen_lr: 1e-5,
        iter_num_gen: 1,
        alpha: 0.2,
        dis_hidden: 10000,
        dis_output_activation: 'sigmoid',
        dis_lr: 1e-5,
        iter_num_dis: 1,
        add_Expo: True,
        use_step: True,
        thread: 0.001,
        bind_train_epochs: 20,
        topK_test: [5, 10, 20, 50, 100],
        record_interval: 200,
        log_path: 'log'
    },
    'music': {
        train: True,
        dataset_no: 1,
        fold_no: [1, 3, 4], # 0 | 1 | 2 | 3 | 4
        train_batch_size: 10000,
        test_batch_size: 10000,
        epochs: 60000,
        gen_hidden: 20000,
        gen_output_activation: 'sigmoid',
        gen_lr: 1e-5,
        iter_num_gen: 1,
        alpha: 0.19,
        dis_hidden: 10000,
        dis_output_activation: 'sigmoid',
        dis_lr: 1e-5,
        iter_num_dis: 1,
        add_Expo: True,
        use_step: True,
        thread: 0.001,
        bind_train_epochs: 20,
        topK_test: [ 5, 10, 20, 50, 100 ],
        record_interval: 200,
        log_path: 'log'
    },
    'products': {
        train: True,
        dataset_no: 2,
        fold_no: [1, 2, 3, 4], # 0 | 1 | 2 | 3 | 4
        train_batch_size: 10000,
        test_batch_size: 10000,
        epochs: 100000,
        gen_hidden: 20000,
        gen_output_activation: 'sigmoid',
        gen_lr: 1e-5,
        iter_num_gen: 1,
        alpha: 0.22,
        dis_hidden: 10000,
        dis_output_activation: 'sigmoid',
        dis_lr: 1e-5,
        iter_num_dis: 1,
        add_Expo: True,
        use_step: True,
        thread: 0.001,
        bind_train_epochs: 20,
        topK_test: [ 5, 10, 20, 50, 100 ],
        record_interval: 200,
        log_path: 'log'
    },
    'games': {
        train: True,
        dataset_no: 3,
        fold_no: [ 0 ], # 0 | 1 | 2 | 3 | 4
        train_batch_size: 10000,
        test_batch_size: 10000,
        epochs: 60000,
        gen_hidden: 20000,
        gen_output_activation: 'sigmoid',
        gen_lr: 1e-5,
        iter_num_gen: 1,
        alpha: 0.2,
        dis_hidden: 10000,
        dis_output_activation: 'sigmoid',
        dis_lr: 1e-5,
        iter_num_dis: 1,
        add_Expo: True,
        use_step: True,
        thread: 0.001,
        bind_train_epochs: 20,
        topK_test: [ 5, 10, 20, 50, 100 ],
        record_interval: 200,
        log_path: 'log'
    }
}